apiVersion: v2
name: tibber-exporter
version: 1.4.1
appVersion: 15
description: Helm chart for Tibber prometheus exporter
type: application
keywords:
  - tibber
  - prometheus
  - grafana
  - monitoring
home: https://github.com/terjesannum/tibber-exporter
maintainers:
  - name: Terje Sannum
    email: terje@offpiste.org
    url: https://github.com/terjesannum
annotations:
  artifacthub.io/images: |
    - name: tibber-exporter
      image: ghcr.io/terjesannum/tibber-exporter:15
  artifacthub.io/screenshots: |
    - title: Grafana dashboard
      url: https://raw.githubusercontent.com/terjesannum/tibber-exporter/master/grafana/dashboard.png
