tibberToken: ""

serviceMonitor:
  enabled: false
  labels: {}
  interval: # 5s
  scrapeTimeout: # 10s
  
image:
  repository: ghcr.io/terjesannum/tibber-exporter
  tag: 13
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  allowPrivilegeEscalation: false

resources: {}
  # limits:
  #   cpu: 20m
  #   memory: 32Mi
  # requests:
  #   cpu: 10m
  #   memory: 32Mi
