tibberToken: ""

# liveMeasurements can be used to initialize the exporter with
# a list of homes that has live measurements. Used to ensure
# live measurements is started as # the Tibber API not always
# report correct in features->realTimeConsumptionEnabled
liveMeasurements: []
# - "4cda7b18-0bdf-5669-65b4-e24253f8a6d7"
# - "68e3a27e-8a79-42e2-8379-f5e1ab1189de"

serviceMonitor:
  enabled: false
  labels: {}
  interval: # 5s
  scrapeTimeout: # 10s
  
image:
  repository: ghcr.io/terjesannum/tibber-exporter
  # Overrides the image tag whose default is the chart appVersion
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  allowPrivilegeEscalation: false

resources: {}
  # limits:
  #   cpu: 20m
  #   memory: 32Mi
  # requests:
  #   cpu: 10m
  #   memory: 32Mi
