apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "tibber-exporter.fullname" . }}
  labels:
    {{- include "tibber-exporter.labels" . | nindent 4 }}
stringData:
  token: '{{ required "Tibber token is required" .Values.tibberToken }}'
