---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tibber-exporter.fullname" . }}
  labels:
    {{- include "tibber-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "tibber-exporter.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
