apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tibber-exporter.fullname" . }}
  labels:
    {{- include "tibber-exporter.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "tibber-exporter.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "tibber-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if not .Values.serviceMonitor.enabled }}
        prometheus.io/scrape: 'true'
        {{- end }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "tibber-exporter.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: tibber-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: TIBBER_TOKEN
              value: '{{ required "Tibber token is required" .Values.tibberToken }}'
          args:
            {{- range .Values.liveMeasurements}}
            - --live
            - "{{ . }}"
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
